Repository cyfitech/cris-core, pull requests merged in 2022-12, with the labels that each got.

#114 Add llvm-13 builds and use llvm-13 for sanitizers
  .github/workflows/build.yml
  Makefile
Labels: enhancement

#106 Add message recorder config file
  BUILD
  src/config/recorder_config.cc
  src/config/recorder_config.h
  tests/config_test.cc
Labels: enhancement

#101 DB Close and Reopen for RecordFile
  src/msg_recorder/record_file.cc
  src/msg_recorder/record_file.h
  tests/BUILD
  tests/record_file_db_reopen_test.cc
Labels: enhancement

#119 Add libbenchmark-dev (Google Benchmark)
  docker/Dockerfile
Labels: enhancement

#123 [CI] Use docker image that has libbenchmark-dev (Google Benchmark)
  .github/workflows/build.yml
  Makefile
Labels: enhancement

#122 Add util function `InverseMapping`
  src/utils/mapping.h
  tests/BUILD
  tests/mapping_test.cc
Labels: enhancement

#124 Replace `not` with `!`.
  src/utils/mapping.h
Labels: bug

#120 Enable Stacktrace in Unit Tests
  tests/BUILD
  tests/utils/cris_gtest_main.cc
Labels: bug

#110 Upgrade clang-tidy config
  .clang-tidy
  src/config/config.cc
  src/config/config.h
  src/msg/message.h
  src/msg/node.cc
  src/msg/node.h
  src/msg_recorder/record_file.cc
  src/msg_recorder/recorder.h
  src/msg_recorder/replayer.cc
  src/msg_recorder/replayer.h
  src/msg_recorder/tools/ldb_record_convert.cc
  src/sched/job_runner.cc
  src/sched/spin_impl.cc
  src/signal/cr_signal.cc
  src/timer/timer.h
  src/timer/timer_enable.cc
  src/utils/defs.cc
  src/utils/defs.h
  src/utils/time.cc
  tests/config_test.cc
  tests/job_runner_test.cc
  tests/mapping_test.cc
  tests/msg_recorder_test.cc
  tests/record_file_db_reopen_test.cc
  tests/record_key_test.cc
Labels: enhancement

#116 Recorder snapshot feature with single time interval
  src/msg_recorder/recorder.cc
  src/msg_recorder/recorder.h
  tests/BUILD
  tests/msg_recorder_test.cc
  tests/recorder_snapshot_test.cc
  tests/recorder_snapshot_tsan_suppressions.txt
Labels: enhancement, help wanted

#121 Introduce TryRunImmediately to the JobRunner
  src/sched/job_runner.cc
  src/sched/job_runner.h
  src/signal/cr_signal.cc
  tests/job_runner_test.cc
Labels: enhancement
