Repository cyfitech/cris-core, pull requests merged in 2023-03, with the labels that each got.

#177 Make the snapshot unit test temporarily flaky
  tests/BUILD
Labels: enhancement

#179 Add status callback functions after each snapshot generation
  src/msg_recorder/recorder.cc
  src/msg_recorder/recorder.h
Labels: enhancement

#182 Unify command check and add geo routing for pip index.
  Makefile
  scripts/auth_github_ssh.sh
  scripts/bazel_pull.sh
  scripts/release_docker_legacy.sh
  scripts/sync_infra.sh
Labels: bug, enhancement

#181 Add status callback functions to the snapshot lifecycle
  src/msg_recorder/recorder.cc
  src/msg_recorder/recorder.h
Labels: enhancement

#187 Sync build infra
  .github/workflows/build.yml
  Makefile
Labels: enhancement

#186 Allow MessageRecorder to use differenct record file dir hierarchy
  src/msg_recorder/recorder.cc
  src/msg_recorder/recorder.h
Labels: enhancement

#192 Install latest libomp on all distros.
  docker/Dockerfile
Labels: enhancement

#190 Add auto rolling feature for record files
  BUILD
  src/msg_recorder/record_file.cc
  src/msg_recorder/record_file.h
  src/msg_recorder/recorder.cc
  src/msg_recorder/recorder.h
  src/msg_recorder/rolling_helper.cc
  src/msg_recorder/rolling_helper.h
  src/utils/time.cc
  src/utils/time.h
  tests/BUILD
  tests/rolling_helper_test.cc
Labels: enhancement

#193 Add rolling tests & resolve pending issues for PR #190
  src/msg_recorder/record_file.cc
  src/msg_recorder/record_file.h
  src/msg_recorder/rolling_helper.cc
  src/msg_recorder/rolling_helper.h
  tests/record_file_rolling_test.cc
Labels: enhancement

#200 Suppress Warnings in Boost Headers when Building on MacOS
  src/utils/time.cc
Labels: bug

#198 Fix pip index URL.
  docker/Dockerfile
Labels: bug
